services:
  database:
    container_name: databaseDevOps1
    build:
      context: .docker/db
      dockerfile: Dockerfile
    volumes:
      - "database_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '58010:5432'
    networks:
      - DevOps

  fpm:
    container_name: fpmDevOps1
    build:
      context: .docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - '.:/app'
      - './.docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    ports:
      - '9002:9000'
    depends_on:
      - database
    networks:
      - DevOps

  nginx:
    container_name: nginxDevOps1
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - '.:/app'
      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '9010:80'
    depends_on:
      - fpm
    networks:
      - DevOps

  redis:
    image: redis
    networks:
      - DevOps

  mail:
    image: schickling/mailcatcher
    networks:
      - DevOps

volumes:
  database_data:
    driver: local

networks:
  DevOps:
    driver: bridge
